### ISSUE TITLE
no classifiere found under slidly different conditions

### ISSUE THREAD

**Issue by ArneTillmann** [ArneTillmann/AuDoLab#1]
When I delete those lines 
```python
mistake = papers["text"].iloc[77]

papers = papers[papers["text"] != mistake]

print(len(papers))
```
then in 

```python
nus = np.arange(0.001, 0.5, 0.001)

nus = np.round(nus, 5)

classifier = classification(
    training=papers_tfidf,
    predicting=data_tfidf,
    nus=nus,
    quality_train=0.85,
    min_pred=0.01,
    max_pred=0.1,
)
```
is no classifier found.

**Comment by AFThielmann** [comment]
Yes, that can of course always happen. Especially when you think about, if someone scrapes training data, e.g. about dentistry and tries to classify target data e.g. about politics. It is very likely that the classifier not return a prediction with the given constraints.
In the present case that is indeed unfortunate, but if we change the classifier to, e.g. nus = np.arange(0.0005, 0.5, 0.001) we get several valid classifiers. The document we remove with papers["text"].iloc[77] is a scraping mistake and consists of weird symbols and letters and obviously has a strong impact on the data. To solve the problem alltogether, we should include a warning message with a suggestion to change the hyperparameters when the classifier does not return a prediction
