### ISSUE TITLE
Improve description

### ISSUE THREAD

**Issue by linuxscout** [ArneTillmann/AuDoLab#32]
Hi,
I think that the desciption in README file is too short.
https://github.com/openjournals/joss-reviews/issues/3719 

- [ ] A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is? ** No**

Thanks

**Comment by ArneTillmann** [comment]
Hi @linuxscout,

> =======
> Summary
> =======
> 
> AuDoLab provides a novel approach to one-class document classification for heavily imbalanced datasets, even if labelled training data is not available. Our package enables the user to create specific out-of-domain training data to classify a heavily underrepresented target class in a document dataset using a recently developed integration of Web Scraping, Latent Dirichlet Allocation Topic Modelling and One-class Support Vector Machines. AuDoLab can achieve high quality results even on higly specific classification problems without the need to invest in the time and cost intensive labelling of training documents by humans. Hence, AuDoLab has a broad range of scientific research or business applications.
> 
> Unsupervised document classification is mainly performed to gain insight into the underlying topics of large text corpora. In this process, documents covering highly underrepresented topics have only a minor impact on the algorithm's topic definitions. As a result, underrepresented topics can sometimes be "overlooked" and documents are assigned topic prevalences that do not reflect the underlying content. Thus, labeling underrepresented topics in large text corpora is often done manually and can therefore be very labour-intensive and time-consuming. AuDoLab enables the user to tackle this problem and perform unsupervised one-class document classification for heavily underrepresented document classes.

I've updated the README. Can you tell me, whether this is sufficient for you?

**Comment by linuxscout** [comment]
Thanks. It's great.
